const storiesContent = [
  {
    path: '/john-banister',
    name: 'John Banister',
    occupation: 'Musician',
    biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    video: "https://youtu.be/w--aZlWZr9o",
    transcript: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    teachersnotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus."
  },
  {
    path: '/anne-bracegirdle',
    name: 'Anne Bracegirdle',
    occupation: 'Actress',
    biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    video: "https://youtu.be/KRet2Ym0AhQ",
    transcript: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    teachersnotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus."
  },
  {
    path: '/john-dryden',
    name: 'John Dryden',
    occupation: 'Poet',
    biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    video: "https://youtu.be/PeiAxOkZAgo",
    transcript: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    teachersnotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus."
  },
  {
    path: '/james-elliot',
    name: 'James Elliot',
    occupation: 'City Lawyer',
    biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    video: "https://youtu.be/8P6CiI2DcZc",
    transcript: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    teachersnotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus."
  },
  {
    path: '/william-kendall',
    name: 'William Kendall',
    occupation: 'Theatre Impresario',
    biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    video: "https://youtu.be/o4QV3SaASe4",
    transcript: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    teachersnotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus."
  },
  {
    path: '/george-hutchinson',
    name: 'George Hutchinson',
    occupation: 'Actor',
    biography: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    video: "https://youtu.be/C-x2MgIvrus",
    transcript: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus.",
    teachersnotes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet vehicula dolor, sed ultrices massa varius in. In tellus sapien, ultrices sed orci sed, venenatis dignissim enim. Phasellus in libero nisi. Maecenas non sem nibh. Ut eget efficitur augue. Sed dapibus odio sit amet lorem auctor malesuada. Fusce velit urna, tristique a viverra vel, hendrerit et est. Etiam finibus, magna a laoreet viverra, lacus leo sollicitudin purus, at dictum libero elit at enim. Praesent auctor ipsum ac enim tempor, blandit ultrices nibh consequat. Proin aliquet ipsum et enim sodales, vitae interdum urna accumsan. In hac habitasse platea dictumst. Morbi tincidunt aliquet rutrum. Morbi lobortis risus justo, at molestie ante aliquet vel. Fusce id dui a dui accumsan ultricies eu sed sem. Quisque non felis finibus."
  }
];

export default storiesContent;